import Head from "next/head";
import Image from "next/image";
import Header from "./Header";
const Layout = ({ children, pagina }) => {
  return (
    <>
      <Head>
        <title>Pagina - {pagina}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
    </>
  );
};

export default Layout;
