import Head from "next/head";
import Image from "next/image";
const Layout = ({ children, pagina }) => {
  return (
    <>
      <Head>
        <title>Pagina - {pagina}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h6>Desde Layout principal</h6>
      {children}
    </>
  );
};

export default Layout;
